# Generated by Django 3.1.4 on 2020-12-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery_name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('address3', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=250)),
                ('distance', models.IntegerField()),
                ('difficulty', models.CharField(max_length=30)),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
